In [2]:
import tensorflow as tf

In [3]:
print('version:',tf.__version__)

version: 2.21.0


In [4]:
scaler=tf.constant(5)
print(scaler)

tf.Tensor(5, shape=(), dtype=int32)


In [5]:
print("number only:",scaler.numpy())

number only: 5


In [7]:
print('shape:',scaler.shape)

shape: ()


In [9]:
print('dimension:',scaler.ndim)

dimension: 0


In [10]:
vector=tf.constant([1,2,3])
print('vector:',vector.numpy())

vector: [1 2 3]


In [12]:
print('shape:',vector.shape)

shape: (3,)


In [13]:
print('dimension:',vector.ndim)

dimension: 1


In [14]:
matrix=tf.constant([[1,2,3],
[4,5,6]])
print(matrix)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [16]:
print('values:',matrix.numpy())

values: [[1 2 3]
 [4 5 6]]


In [17]:
print('shape:',matrix.shape)

shape: (2, 3)


In [19]:
print('dimension:',matrix.ndim)

dimension: 2
