In [2]:
import tensorflow as tf

In [3]:
print('version:',tf.__version__)

version: 2.21.0


In [4]:
scaler=tf.constant(5)
print(scaler)

tf.Tensor(5, shape=(), dtype=int32)


In [5]:
print("number only:",scaler.numpy())

number only: 5


In [7]:
print('shape:',scaler.shape)

shape: ()


In [9]:
print('dimension:',scaler.ndim)

dimension: 0


In [10]:
vector=tf.constant([1,2,3])
print('vector:',vector.numpy())

vector: [1 2 3]


In [12]:
print('shape:',vector.shape)

shape: (3,)


In [13]:
print('dimension:',vector.ndim)

dimension: 1


In [14]:
matrix=tf.constant([[1,2,3],
[4,5,6]])
print(matrix)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [16]:
print('values:',matrix.numpy())

values: [[1 2 3]
 [4 5 6]]


In [17]:
print('shape:',matrix.shape)

shape: (2, 3)


In [19]:
print('dimension:',matrix.ndim)

dimension: 2


In [21]:
print('first column:',matrix[:,0].numpy())

first column: [1 4]


In [22]:
tensor_3d=tf.constant([[[1,2,3],
[4,5,6]],

[[5,5,6],
[9,0,1]]])

In [23]:
print('shape:',tensor_3d.shape)

shape: (2, 2, 3)


In [ ]:
print('Dimensions:',tensor_3d)

In [32]:
print('values',tensor_3d.numpy())

values [[[1 2 3]
  [4 5 6]]

 [[5 5 6]
  [9 0 1]]]


In [38]:
print('second matrix second column:',tensor_3d[1][:,2])

second matrix second column: tf.Tensor([6 1], shape=(2,), dtype=int32)


In [39]:
print('values:',tensor_3d[1][:,2].numpy())

values: [6 1]


In [42]:
print(tensor_3d[1,0].numpy())

[5 5 6]


In [3]:
vector=tf.constant([1,2,3,4,5,6])
print(vector)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [6]:
print('first value:',vector[0].numpy())

first value: 1


In [7]:
print('second value:',vector[1].numpy())

second value: 2


In [8]:
print('last value:',vector[-1].numpy())

last value: 6


In [9]:
print('second last value:',vector[-2].numpy())

second last value: 5
