**This notebook is all about slicing**:

In [1]:
import tensorflow as tf

In [2]:
vector=tf.constant([1,2,3,4,5,6])
print(vector)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [3]:
print('first value:',vector[0].numpy())

first value: 1


In [4]:
print('second value:',vector[1].numpy())

second value: 2


In [5]:
print('last value:',vector[-1].numpy())

last value: 6


In [6]:
print('second last value:',vector[-2].numpy())

second last value: 5


In [9]:
print('Index 1 and 2 value:',vector[1:3].numpy())

Index 1 and 2 value: [2 3]


In [16]:
print('From start to index 3',vector[:4].numpy())

From start to index 3 [1 2 3 4]


In [14]:
print('From index 3 to the end:',vector[3:].numpy())

From index 3 to the end: [4 5 6]


In [21]:
print('gap of 2:',vector[::2].numpy())

gap of 2: [1 3 5]


In [24]:
print('reverse order:',vector[::-1].numpy())

reverse order: [6 5 4 3 2 1]


In [29]:
matrix = tf.constant([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print('values:',matrix.numpy())

values: [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [27]:
print('shape:',matrix.shape)

shape: (3, 4)


In [37]:
print('first row:',matrix[0,:].numpy())

first row: [10 20 30 40]


In [43]:
print('first 2 rows:',matrix[0:2, :].numpy())

first 2 rows: [[10 20 30 40]
 [50 60 70 80]]


In [45]:
print("2nd and 3rd column:",matrix[:,1:3].numpy())

2nd and 3rd column: [[ 20  30]
 [ 60  70]
 [100 110]]


In [46]:
small_matrix=matrix[0:2,1:3]
print(small_matrix.numpy())

[[20 30]
 [60 70]]


In [47]:
print('last row:',matrix[-1:,])

last row: tf.Tensor([[ 90 100 110 120]], shape=(1, 4), dtype=int32)


In [48]:
print('last column:',matrix[:,-1])

last column: tf.Tensor([ 40  80 120], shape=(3,), dtype=int32)
