In [1]:
import tensorflow as tf

In [2]:
vector=tf.constant([1,2,3,4,5,6])

In [3]:
print('shape:',vector.shape)

shape: (6,)


In [5]:
print('dimension:',vector.ndim)

dimension: 1


In [6]:
matrix=tf.reshape(vector,shape=(2,3))
print(matrix.numpy())

[[1 2 3]
 [4 5 6]]


In [7]:
print('original shape:',vector.shape)
print('New Shape:',matrix.shape)

original shape: (6,)
New Shape: (2, 3)


In [8]:
print('Original Dimension:',vector.ndim)
print('New Dimension:',matrix.ndim)

Original Dimension: 1
New Dimension: 2


In [9]:
new_matrix=tf.reshape(vector,shape=(3,2))
print(new_matrix.numpy())

[[1 2]
 [3 4]
 [5 6]]


In [10]:
matrix=tf.constant([
[1,2,3],
[4,5,6]

])
print(matrix.numpy())

[[1 2 3]
 [4 5 6]]


In [11]:
vector=tf.reshape(matrix,shape=(6,))
print(vector.numpy())

[1 2 3 4 5 6]
